#!/bin/bash

# Setup main branch on production server
# This script helps configure the production server to use main branch instead of master

set -e

echo "🔧 Setting up main branch on production"
echo "=================================="
echo ""
echo "This script will help you configure the production server."
echo "You need to run these commands on the production server via SSH."
echo ""
echo "Steps to execute on production server:"
echo ""
echo "1. Connect to production:"
echo "   ssh alfares"
echo ""
echo "2. Navigate to ai-microservice directory:"
echo "   cd ~/Documents/Github/ai-microservice"
echo ""
echo "3. Fetch latest changes from remote:"
echo "   git fetch origin"
echo ""
echo "4. Check current branch:"
echo "   git branch"
echo ""
echo "5. Switch to main branch (if it exists locally):"
echo "   git checkout main"
echo ""
echo "   OR if main doesn't exist locally, create it from remote:"
echo "   git checkout -b main origin/main"
echo ""
echo "6. Set main as the default branch:"
echo "   git branch --set-upstream-to=origin/main main"
echo ""
echo "7. Verify the setup:"
echo "   git branch -vv"
echo "   git status"
echo ""
echo "8. Pull latest changes:"
echo "   git pull"
echo ""
echo "=================================="
echo "✅ Follow these steps on production server"
